CREATE TABLE users (
    user_id SERIAL PRIMARY KEY,
    user_name VARCHAR(100) NOT NULL,
    user_password VARCHAR(255) NOT NULL,
    phone BIGINT UNIQUE NOT NULL CHECK (phone BETWEEN 6000000000 AND 9999999999),
    user_role VARCHAR(15) NOT NULL CHECK (user_role IN ('ASHA', 'SUPERVISOR', 'PATIENT')),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);